from __future__ import annotations

from twsim.models import ActionDef, ActionSlot, EndingRule

ACTIONS: dict[str, ActionDef] = {
    "naval_drill": ActionDef(
        key="naval_drill",
        slot=ActionSlot.PRIMARY,
        label="海军高强度演训",
        description="提高压制力，但会拉高紧张与国际风险。",
        tension=10,
        pressure=12,
        risk=8,
        strain=4,
        readiness=6,
        opponent_stability=-5,
    ),
    "precision_patrol": ActionDef(
        key="precision_patrol",
        slot=ActionSlot.PRIMARY,
        label="精确巡航封控",
        description="稳步施压，风险中等。",
        tension=6,
        pressure=9,
        risk=5,
        strain=3,
        readiness=4,
        opponent_stability=-4,
    ),
    "port_quarantine": ActionDef(
        key="port_quarantine",
        slot=ActionSlot.PRIMARY,
        label="重点港口隔离",
        description="强化海空封控，压缩对手外部补给与航运秩序。",
        tension=5,
        pressure=10,
        risk=4,
        strain=2,
        readiness=3,
        opponent_stability=-4,
    ),
    "joint_fire_strike": ActionDef(
        key="joint_fire_strike",
        slot=ActionSlot.PRIMARY,
        label="联合火力瘫痪打击",
        description="高烈度打击关键节点，收益高但升级代价明显。",
        tension=12,
        pressure=16,
        risk=11,
        strain=7,
        readiness=-3,
        opponent_stability=-8,
    ),
    "drone_saturation": ActionDef(
        key="drone_saturation",
        slot=ActionSlot.PRIMARY,
        label="无人机饱和袭扰",
        description="以低成本平台持续消耗防空与指挥链。",
        tension=7,
        pressure=10,
        risk=5,
        strain=3,
        readiness=1,
        opponent_stability=-5,
    ),
    "cyber_probe": ActionDef(
        key="cyber_probe",
        slot=ActionSlot.SECONDARY,
        label="网络侦搜",
        description="获取信息并小幅削弱对手稳定。",
        tension=2,
        pressure=5,
        risk=2,
        strain=1,
        readiness=2,
        opponent_stability=-3,
    ),
    "logistics_recovery": ActionDef(
        key="logistics_recovery",
        slot=ActionSlot.SECONDARY,
        label="后勤整补",
        description="提升战备并缓和内压。",
        tension=-3,
        pressure=0,
        risk=-2,
        strain=-5,
        readiness=10,
        opponent_stability=0,
    ),
    "electronic_jamming": ActionDef(
        key="electronic_jamming",
        slot=ActionSlot.SECONDARY,
        label="电磁压制",
        description="扰乱雷达与通信，配合前沿打击制造局部优势。",
        tension=3,
        pressure=4,
        risk=2,
        strain=1,
        readiness=1,
        opponent_stability=-2,
    ),
    "reserve_mobilization": ActionDef(
        key="reserve_mobilization",
        slot=ActionSlot.SECONDARY,
        label="后续梯队动员",
        description="前推部队与联勤准备，为高强度阶段蓄力。",
        tension=1,
        pressure=1,
        risk=1,
        strain=3,
        readiness=8,
        opponent_stability=0,
    ),
    "civil_fleet_requisition": ActionDef(
        key="civil_fleet_requisition",
        slot=ActionSlot.SECONDARY,
        label="民船征用预置",
        description="扩充后续运输与装卸能力，但会增加国内承压。",
        tension=2,
        pressure=3,
        risk=2,
        strain=4,
        readiness=6,
        opponent_stability=-1,
    ),
    "diplomatic_signal": ActionDef(
        key="diplomatic_signal",
        slot=ActionSlot.INFO,
        label="外交沟通",
        description="降低外部风险，但压制效果减弱。",
        tension=-4,
        pressure=-2,
        risk=-6,
        strain=-1,
        readiness=0,
        opponent_stability=2,
    ),
    "info_campaign": ActionDef(
        key="info_campaign",
        slot=ActionSlot.INFO,
        label="信息战宣示",
        description="提高施压与认知影响，风险小幅上升。",
        tension=3,
        pressure=6,
        risk=3,
        strain=2,
        readiness=0,
        opponent_stability=-2,
    ),
    "legal_announcement": ActionDef(
        key="legal_announcement",
        slot=ActionSlot.INFO,
        label="法理定调与通告",
        description="用法律与公告包装行动，稳步扩大施压合法性。",
        tension=1,
        pressure=3,
        risk=0,
        strain=0,
        readiness=0,
        opponent_stability=-1,
    ),
    "market_stabilization": ActionDef(
        key="market_stabilization",
        slot=ActionSlot.INFO,
        label="市场稳定措施",
        description="压低恐慌与外溢冲击，换取更稳的持续行动空间。",
        tension=-2,
        pressure=0,
        risk=-1,
        strain=-4,
        readiness=1,
        opponent_stability=0,
    ),
    "external_deterrence": ActionDef(
        key="external_deterrence",
        slot=ActionSlot.INFO,
        label="对外威慑喊话",
        description="警告第三方勿介入，增加压迫感但抬升风险。",
        tension=2,
        pressure=3,
        risk=2,
        strain=0,
        readiness=0,
        opponent_stability=-1,
    ),
    "united_front_pressure": ActionDef(
        key="united_front_pressure",
        slot=ActionSlot.INFO,
        label="分化与认知施压",
        description="放大恐慌与分歧，试图削弱对手社会韧性。",
        tension=1,
        pressure=4,
        risk=1,
        strain=1,
        readiness=0,
        opponent_stability=-3,
    ),
}

AI_RESPONSES = {
    "deescalate": {"tension": -6, "risk": -4, "pressure": -3, "opp": 3},
    "defensive_reinforce": {"tension": 4, "risk": 3, "pressure": -2, "opp": 5},
    "counter_pressure": {"tension": 6, "risk": 6, "pressure": -1, "opp": 2},
}

AI_RESPONSE_LABELS = {
    "deescalate": "外部降温与内线整补",
    "defensive_reinforce": "滩岸戒备与节点固守",
    "counter_pressure": "后备动员与外援争取",
}

EVENTS = [
    ("美日侦巡加密", {"risk": 5, "tension": 2}),
    ("台军后备动员加速", {"risk": 3, "tension": 2}),
    ("北部港口航运改道", {"risk": 4, "strain": 2}),
    ("海缆异常引发抢修", {"risk": 2, "tension": 1}),
    ("民船征用推进顺利", {"strain": 2, "readiness": 4}),
    ("联勤节点一度拥堵", {"strain": 5, "readiness": -3}),
    ("沿海装卸效率提升", {"strain": -3, "readiness": 3}),
    ("离岛疏散预案启动", {"risk": 3, "tension": 3}),
    ("能源市场剧烈波动", {"risk": 2, "strain": 5}),
    ("港口保险费暴涨", {"risk": 4, "strain": 3}),
    ("外部斡旋成功", {"risk": -5, "tension": -2}),
    ("舆情安抚暂时奏效", {"risk": -2, "strain": -3}),
    ("民生物资补给稳定", {"strain": -4, "readiness": 2}),
    ("误判警报", {"risk": 8, "tension": 5}),
    ("无重大事件", {}),
]

ENDINGS: list[EndingRule] = [
    EndingRule("coercive_success", "威慑达成", "多域封控奏效，对手承压明显且外部升级仍可控。"),
    EndingRule("costly_success", "高成本达成", "目标虽达成，但外部介入与内部承压已逼近极限。"),
    EndingRule("frozen_advantage", "冻结优势", "未能彻底压垮对手，但形成了更有利的高压僵局。"),
    EndingRule("international_escalation", "国际失控升级", "联盟介入与区域外溢持续放大，原定框架失控。"),
    EndingRule("domestic_collapse", "内部承压失衡", "持续动员与经济反噬拖垮了战备与国内承受力。"),
    EndingRule("strategic_failure", "战略失效", "回合结束仍未建立足够压制，危机被拖入无果消耗。"),
]
